name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: paulhatch/semantic-version@v5.4.0
        id: version
      
      - name: Change version in data.yaml
        run: |
          sed -i "s/version: \".*\"/version: \"${{ steps.version.outputs.version }}\"/" data.yaml
        shell: bash
      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ steps.version.outputs.version }}"
          commit_user_name: "github-actions"
  ci:
    needs: versioning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run YAML validation
      run: python validate_yaml.py schema.json data.yaml
    
    - name: Generate Documentation
      run: python generate_doc.py data.yaml -o README.md
    
    - name: Remove README.md from gitignore
      run: |
        sed -i '/README.md/d' .gitignore
      shell: bash

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update documentation"
        commit_user_name: "github-actions"
        file_pattern: README.md
    
