name: Validate YAML

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run YAML validation
      run: python validate_yaml.py schema.json data.yaml
    
    - name: Generate Documentation
      run: python generate_doc.py data.yaml -o README.md
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update documentation"
        commit_user_name: "github-actions"
        file_pattern: README.md
    
