name: Bump Version

on:
  push:
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: paulhatch/semantic-version@v5.4.0
        id: version
      
      - name: Change version in data.yaml
        run: |
          sed -i "s/version: \".*\"/version: \"${{ steps.version.outputs.version }}\"/" data.yaml
        shell: bash
      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ steps.version.outputs.version }}"
          commit_user_name: "github-actions"